#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Windows Boot Manager' --class windows --class os {
	savedefault
	insmod part_gpt
	insmod fat
	search --no-floppy --fs-uuid --set=root C62E-7FE7
	chainloader /efi/Microsoft/Boot/bootmgfw.efi
}
